apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kokoro-tts-server-voices
  labels:
    app: kokoro-tts-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
